name: Trigger Action on a CRON Schedule
on:
  schedule:
  #runs "At 11:00 on every day-of-week from Monday through Friday"
    - corn: '0 11 * * 1-5'
jobs:
  build:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    #Step represent a sequence of tasks that will be execute as part of the job

    steps:
    # Check-out your repository under $GITHUB_WORKSPACE, so your job cab access it
      - uses: actions/checkout@v3
